controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_pitch_right
      - arm_roll_right
      - hand_right

      - arm_pitch_left
      - arm_roll_left
      - hand_left

      - leg_yaw_right
      - leg_roll_right
      - leg_upper_right
      - leg_under_right
      - foot_pitch_right
      - foot_roll_right

      - leg_yaw_left
      - leg_roll_left
      - leg_upper_left
      - leg_under_left
      - foot_pitch_left
      - foot_roll_left

    command_interfaces:
      # - position
      # - velocity
      - effort

    state_interfaces:
      - position
      - velocity

    # for torque 0.7
    # gains:
    #   arm_pitch_right  : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    #   arm_roll_right   : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    #   hand_right       : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
      
    #   arm_pitch_left   : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    #   arm_roll_left    : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    #   hand_left        : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
      
    #   leg_yaw_right    : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    #   leg_roll_right   : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    #   leg_upper_right  : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    #   leg_under_right  : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    #   foot_pitch_right : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    #   foot_roll_right  : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    
    #   leg_yaw_left     : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    #   leg_roll_left    : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    #   leg_upper_left   : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    #   leg_under_left   : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    #   foot_pitch_left  : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
    #   foot_roll_left   : {p: 35500.0, i: 0.1, d: 85.0, i_clamp: 2.5}
      
    gains:
      arm_pitch_right  : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      arm_roll_right   : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      hand_right       : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      
      arm_pitch_left   : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      arm_roll_left    : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      hand_left        : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      
      leg_yaw_right    : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      leg_roll_right   : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      leg_upper_right  : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      leg_under_right  : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      foot_pitch_right : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      foot_roll_right  : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
    
      leg_yaw_left     : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      leg_roll_left    : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      leg_upper_left   : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      leg_under_left   : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      foot_pitch_left  : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
      foot_roll_left   : {p: 100.0, i: 0.1, d: 0.2, i_clamp: 2.5}
