<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro" name="eglantyne">
    <xacro:macro name="box_link" params="name x y z ofsx ofsy ofsz mass">
        <link name = "${name}">
            <visual>
                <geometry>
                    <box size="${x * 0.001} ${y * 0.001} ${z * 0.001}"/>
                </geometry>
                <material name="silver">
                    <color rgba="0.75 0.75 0.75 1"/>
                </material>
                <origin rpy="0 0 0" xyz="${ofsx * 0.001} ${ofsy * 0.001} ${ofsz * 0.001}"/>
            </visual>

            <collision>
                <geometry>
                    <box size="${x * 0.001} ${y * 0.001} ${z * 0.001}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="${ofsx * 0.001} ${ofsy * 0.001} ${ofsz * 0.001}"/>
            </collision>

            <inertial>
                <mass value="${mass}"/>
                <inertia ixx="${(1/12) * mass * (y*y + z*z) * 0.000001}" ixy="0.0" ixz="0.0"
                         iyy="${(1/12) * mass * (x*x + z*z) * 0.000001}" iyz="0.0"
                         izz="${(1/12) * mass * (x*x + y*y) * 0.000001}" />
                <origin rpy="0 0 0" xyz="${ofsx * 0.001} ${ofsy * 0.001} ${ofsz * 0.001}"/>
            </inertial>
        </link>
    </xacro:macro>


    <xacro:macro name="cylinder_link" params="name length radious ofsx ofsy ofsz mass">
        <link name = "${name}">
            <visual>
                <geometry>
                    <cylinder length="${length * 0.001}" radius="${radious * 0.001}"/>
                </geometry>
                <material name="silver">
                    <color rgba="0.75 0.75 0.75 1"/>
                </material>
                <origin rpy="0 0 0" xyz="${ofsx * 0.001} ${ofsy * 0.001} ${ofsz * 0.001}"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder length="${length * 0.001}" radius="${radious * 0.001}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="${ofsx * 0.001} ${ofsy * 0.001} ${ofsz * 0.001}"/>
            </collision>

            <inertial>
                <mass value="${mass}"/>
                <inertia ixx="${( ( (1/4) * mass * radious*radious ) + ( (1/12)* mass * length*length ) )* 0.000001}" ixy="0.0" ixz="0.0"
                         iyy="${( ( (1/4) * mass * radious*radious ) + ( (1/12)* mass * length*length ) )* 0.000001}" iyz="0.0"
                         izz="${(1/2) * mass * radious*radious  * 0.000001}" />
                <origin rpy="0 0 0" xyz="${ofsx * 0.001} ${ofsy * 0.001} ${ofsz * 0.001}"/>
            </inertial>
        </link>
    </xacro:macro>
</robot>
